version: '3.5'

services:
  module-management-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: module-management-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8091:80
    networks:
      backend:
        aliases:
          - module-management-app

  module-management-db:
    image: mysql:5.7
    container_name: module-management-db
    ports:
      - 33067:3306
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network
